### ISSUE TITLE
Missing vc:minVersion

### ISSUE THREAD

**Issue by tbm0115** [mtconnect/schema#10]
https://github.com/mtconnect/schema/blob/da980b940b29bf539626f84320d835caaab27e00/MTConnectDevices_1.3_1.0.xsd#L34

Missing `vc:minVersion` in root. Should be '1.1' like in 1.3.0.

**Comment by wsobel** [comment]
This is the 1.0 compatible version of the schema, there are extensibility limitations due to the limitations of XML Schema 1.1. Min Version was added as part of 1.1 and would invalidate the schema.

Many validators cannot handle 1.1, so we offer this to replace the 1.1 schema if desired. 

Best,
W
