### ISSUE TITLE
Missing ClockTime

### ISSUE THREAD

**Issue by espinhogr** [mtconnect/schema#2]
Hi, 
I was checking your standard and I've noticed that in your [specification document](https://static1.squarespace.com/static/54011775e4b0bc1fe0fb8494/t/557acdbae4b0d4d1d367b696/1434111418321/MTC_Part_3_Streams_1+3+1_FINAL.pdf) you allow a `CLOCK_TIME` Data Element while your [.xsd](https://github.com/mtconnect/schema/blob/master/MTConnectStreams_1.3_1.0.xsd) does not mention it.

**Comment by wsobel** [comment]
Clock time is now in the 1.3 schemas.
