### ISSUE TITLE
V1.5 validation issue on subType="COMPLETE"

### ISSUE THREAD

**Issue by skibum1869** [mtconnect/schema#6]
When using PROCESS_TIME, the subType COMPLETE does not validate as it is not an attribute of DataItem.

`<DataItem id="job_end_time" type="PROCESS_TIME" subType="COMPLETE" category="EVENT"></DataItem>`

gives the following error 

Severity: error
Description: The value 'COMPLETE' of attribute 'subType' on element 'DataItem' is not valid with respect to its type, 'DataItemSubEnumType'.

The callout for this type is on page 140 of part 2 version 1.5.
![image](https://user-images.githubusercontent.com/15605269/79690708-6b108d80-8221-11ea-85f8-75e6f9b5c1bf.png)

**Comment by wsobel** [comment]
Thanks, I’ll check this out and make sure it is there. The schema is generated from the docs and there are a few annotations that are sometimes missing. 

Best,
W

(Sent from mobile)

**Comment by wsobel** [comment]
I have just pushed the change. Please get the latest schema files. I will re-release the agent if they are correct.

**Comment by skibum1869** [comment]
That fixed the issue, it successfully validated.
