### ISSUE TITLE
Missing Pallet ID in schema version 1.2

### ISSUE THREAD

**Issue by hulinning2** [mtconnect/schema#7]
Hi, 
Pallet ID is documented in the public release but it is not in the schema 1.2.

Can you check?

File http://localhost:5000/current or probe or sample  is not valid.
	Element <PalletId> is not allowed under element <Events>.
		Reason: The following elements are expected at this location (see below)
			'Event'
			'Code'
			'Block'
			'Line'
			'PowerStatus'
			'PowerState'
			'PartCount'
			'Direction'
			'Program'
			'Execution'
			'ControllerMode'
			'ToolAssetId'
			'ToolId'
			'ToolNumber'
			'PartId'
			'DoorState'
			'WorkholdingId'
			'RotaryMode'
			'ActiveAxes'
			'CoupledAxes'
			'AxesCoupling'
			'Message'
			'EmergencyStop'
			'Availability'
			'ActuatorState'
			'PathMode'
			'LinePowerState'
			'ControlPowerState'
			'AssetChanged'
			'Alarm'
		Annotations of element 'Events' (see below)
			A collection of events
		Annotations of type 'EventsType' (see below)
			A collection of events and alarms for this component
		Error location: MTConnectStreams / Streams / DeviceStream / ComponentStream / Events / PalletId
		Details
			cvc-complex-type.1.4: Element <PalletId> unexpected by type 'EventsType' of element <Events>.
			cvc-type.3.2: Element <Events> is not valid with respect to type definition 'EventsType'.
			cvc-elt.5.2.1: The element <Events> is not valid with respect to the actual type definition 'EventsType'.

Thanks

**Comment by hulinning2** [comment]
Will, 
Would you check out this issue? 
Thanks

**Comment by hulinning2** [comment]
It is in 1.2 release but it is removed in 1.5 release

**Comment by BASA6850** [comment]
Hi,
is there a solution yet?
Thanks.
